#if !defined(LINKEDLIST_TAG) || !defined(LINKEDLIST_TYPE) || !defined(LINKEDLIST_NODE_TAG)
#error No type was set for LinkedList.
#endif

#define LINKEDLIST_METHOD_CONCAT(className, methodName) className##methodName
#define LINKEDLIST_METHOD_WRAPPER(className, methodName) LINKEDLIST_CONCAT(className, methodName)
#define LINKEDLIST_METHOD(methodName) LINKEDLIST_METHOD_WRAPPER(LINKEDLIST_TAG, methodName)



typedef struct LINKEDLIST_TAG LINKEDLIST_TAG;
typedef struct LINKEDLIST_NODE_TAG LINKEDLIST_NODE_TAG;

struct LINKEDLIST_NODE_TAG {
  LINKEDLIST_TYPE value;
  LINKEDLIST_NODE_TAG *next;
};

struct LINKEDLIST_TAG {
  LINKEDLIST_NODE_TAG *head;
};

#undef LINKEDLIST_TAG
#undef LINKEDLIST_TYPE
#undef LINKEDLIST_METHOD_CONCAT
#undef LINKEDLIST_METHOD
#undef LINKEDLIST_METHOD_WRAPPER

#undef LINKEDLIST_NODE_TAG
